server:
    port: 8082
spring:
    application:
      name: book-service
    profiles:
      active: dev
    datasource:
        password: password
        url: jdbc:mysql://localhost:3306/book_db?useSSL=false
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
    
    config:
       import: "configserver:http://localhost:8090/"

management:
  endpoints:
    web:
      exposure:
        include: info, shutdown
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

info:
  app:
    name: book-service
    description: Library Service Application
    version: 1.0.1
    
logging:
  level:
    web: DEBUG
    
    